### PR TITLE
[FIX] fix orders data processing

### PR DESCRIPTION
**Pull request by darkdarkdragon**
don't clip TakerPays field of order object
to bidder's own funds

### CODE REVIEW

**Comment by vhpoet** [comment]
Can you explain this @darkdarkdragon

**Comment by darkdarkdragon** [comment]
@vhpoet I did this because I'm getting this offer:
```javascript
{
Account:"rfTiZ53FW6aXcY9TFXQbZMsHQeP4h6Dgkh",
TakerGets:
{ currency:"CNY", issuer:"rKiCet8SdvWxPXnAgYarFUXMh1zCPz432Y", value:"200.1827015496725" }
,
TakerPays:"2453138425",
is_fully_funded:false,
owner_funds:"200.178697975713",
taker_gets_funded:"200.178697975713",
taker_pays_funded:"1226544681"
}
```
with price 0.0816
Value of taker_pays_funded in this object clearly not right.
As I see now, we should do 
```javascript
d.TakerPays.value = d.taker_gets_funded * price
```

or made somewhere else fix so we don't get such objects

**Comment by darkdarkdragon** [comment]
@vhpoet I've found source of the problem.

[Here](https://github.com/ripple/ripple-lib/blob/develop/src/js/ripple/orderbook.js#L456) taker_pays_funded calculated as percent of all the account's offers, but in in RT on trade tab it is used as if it is full value of this one offer.

**Comment by darkdarkdragon** [comment]
@vhpoet I've made changes to calc TakerPays using taker_gets_funded and price

**Comment by vhpoet** [comment]
@darkdarkdragon thanks for looking at this, but this problem is in the ripple-lib and it needs to be fixed there. I think they already have a release candidate with the fix. Closing this for now.

**Pull request closed without merging**
