### PR TITLE
[FIX] Use !== to compare with 0

### PR DESCRIPTION
**Pull request by jublo**

### CODE REVIEW

**Comment by mrajvanshy** [comment]
LGTM

**Comment by yongsoo** [comment]
LGTM

**Comment by vhpoet** [comment]
@jublo did you test this? are you sure the numbers actually have a number format and are not strings?

**Comment by jublo** [comment]
@vhpoet Actually you’re right:

objects

But how to get the JSHint error fixed while using a loose comparison?

**Pull request merged**
