### PR TITLE
[FIX]Contacts: use standard notification(RT-2915)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
For creating/deleting/updating contacts use standard
notifications mechanism (that notifications dissapear
after timeout)

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-2915-before

**Comment by darkdarkdragon** [comment]
after
rt-2915-after

**Comment by mrajvanshy** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
