### PR TITLE
[FIX] fix "-0.00" balance (RT-3344)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
after selling all IOU balance was zero but negative,
fix that

### CODE REVIEW

**Comment by vhpoet** [comment]
`effect.balance.is_zero() && effect.balance.is_negative()`

`is_zero` and `is_negative` at the same time?

**Comment by darkdarkdragon** [comment]
Yep. Exactly that happens when you sell all IOUs.

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
