### PR TITLE
[FEATURE] Add Bluzelle gateway for CAD (RT-3441)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Add Bluzelle as a featured gateway for CAD

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3441-after1

**Comment by darkdarkdragon** [comment]
after 2
rt-3441-after2

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
