### PR TITLE
[FIX] Advanced: Disable save button while checking validity (RT-3195)

### PR DESCRIPTION
**Pull request by rht**
Form's default validity is false unless a websocket connection has
been made.

### CODE REVIEW

**Comment by rht** [comment]
Wait, iirc the previous behavior was red box while user is editing the input but without the error message.

**Comment by vhpoet** [comment]
LGTM

**Comment by rht** [comment]
This is still prone to abuse if you do these:
* put cursor at the end of the hostname
* put mouse pointer on top of the save button
* type a character to make the hostname invalid, then a split second later click the save button or press enter

Suggestions:
1. In general, forms with pending validation should be red and without the previous error message.
2. Move rpHostname, rpDest, and rpAvailableName to $asyncvalidators (new since angularjs 1.3.0).

**Comment by rht** [comment]
@vhpoet this should be the correct behavior: button is disabled for every user input regardless of the late validity result.

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
