### PR TITLE
[TASK] tooltip for ~ripplename (RT-3194)

### PR DESCRIPTION
**Pull request by Mesrop**

### CODE REVIEW

**Comment by annatonger** [comment]
Can you attach a before and after screenshot?

**Comment by Mesrop** [comment]
screen shot 2015-02-18 at 22 25 54
screen shot 2015-02-18 at 22 26 22

**Comment by annatonger** [comment]
Where is the link in "Learn more"?

**Comment by Mesrop** [comment]
its a link

**Comment by Mesrop** [comment]
Changed placement to TOP, set underline for Learn more.
screen shot 2015-02-19 at 4 54 52 pm

**Comment by annatonger** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
