### PR TITLE
[TASK] L10n: Update translations

### LINKED ISSUE #2034: Italian translation
"Oblo" as completed the italian translation on Transifex.
Can you update it with the next release/version?

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7229810-italian-translation?utm_campaign=plugin&utm_content=tracker%2F309127&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F309127&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jublo**
Also fixes #2034.

### CODE REVIEW

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Comment by mrajvanshy** [comment]
I think you should rerun the travis build

**Comment by jublo** [comment]
@mrajvanshy You need to go to https://travis-ci.org/ripple/ripple-client/builds/46759309, sign in with your GitHub account and trigger the rebuild yourself, as this option is only available to users with write access to the repo.

**Pull request merged**
