### PR TITLE
[TASK] Currencies: Add XAG, XPT, SGD to dropdown (RT-3200)

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by rht** [comment]
Why is BTC's precision 4, not 8? Same question with LTC.

**Comment by annatonger** [comment]
LGTM

**Comment by rht** [comment]
BTC: 8, XRP: 6, XRR: 15 (because this is an IOU), STR: 0

**Comment by mrajvanshy** [comment]
LGTM

**Comment by rht** [comment]
@mrajvanshy I forgot to add "USD" to the currencies in rippleSingapore in gateways.json.

http://www.xrpga.org/gateways.html is outdated.
There should be a place to GET the most up-to-date gateways.json from one place, instead of manually updating it in rippletrade and every other places.

**Comment by mrajvanshy** [comment]
Yeah we should have some way to automatically get the most up-to-date gateways.json but for now, can you please add USD too?

**Comment by rht** [comment]
This will be in the BTC-XRP-LTC PR after I fix the merge conflict.

**Comment by rht** [comment]
@mrajvanshy While we are at this featured gateway integration thing.

Why lots of code duplication at three-letter-currency.js and three-letter-currency.jade ?

This should be made more declarative than the currently "imperative" implementation.
Maybe add a field "featured: bool" in gateways.json.

What if snapswap suddenly supports Barbados Dollar (BBD) and why is this not in the currency list of the featured gateway when it happens?

**Pull request merged**
