### PR TITLE
[TASK] Add GateHub gateway (RT-3486)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Add GateHub gateway to the Gateways list

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3486-after1

**Comment by darkdarkdragon** [comment]
rt-3486-after2

**Comment by darkdarkdragon** [comment]
rt-3486-after3

**Comment by mrajvanshy** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
