### PR TITLE
[TASK] Notifications bubble font family (RT-2996)

### PR DESCRIPTION
**Pull request by Mesrop**

### CODE REVIEW

**Comment by mrajvanshy** [comment]
LGTM

**Comment by rippletravis** [comment]
Is there a reason that the notification bubbles aren't covered by a site-wide Open Sans font declaration?

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by jublo** [comment]
LGTM.

Would like to know the answer to [this](https://github.com/ripple/ripple-client/pull/2071#issuecomment-69233521), too.

**Comment by Mesrop** [comment]
@jublo @rippletravis you are right, there were some font owerwrite. I've changed the HTML structure slightly to have it on the right way and the font fixed automatically. so removed also the font definition.

**Comment by mrajvanshy** [comment]
Now in your commit, it doesn't look like you changed anything to do with the fonts. Is that right?

**Comment by Mesrop** [comment]
Yes, I've corrected the HTML structure, so it is using the site-wide defined font.

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
