### PR TITLE
[TASK] Send,Exchange: Add exchange rate (RT-3082)

### PR DESCRIPTION
**Pull request by rht**
And also set IOU precision limit to 15 to be consistent with the wiki

### CODE REVIEW

**Comment by rht** [comment]
Send before
2015-02-22-135754_851x414_scrot
Send after
2015-02-22-135356_855x517_scrot

**Comment by rht** [comment]
Exchange before
2015-02-22-135721_850x437_scrot
Exchange after
2015-02-22-135433_865x468_scrot

**Comment by annatonger** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
