### PR TITLE
[FIX] Advanced Trade: remove one step (RT-3271)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Do not show "Submit another order" screen
after placing an order

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3271-before

**Comment by darkdarkdragon** [comment]
after
rt-3271-after

**Comment by vhpoet** [comment]
LGTM

**Comment by yongsoo** [comment]
Do we want the module to move?  I'm assuming the notification will disappear. What if the user is trying to click and do a click trade but the notification moves?  Maybe we should move the notification to a place where it won't move the input fields? @vhpoet

**Comment by vhpoet** [comment]
@yongsoo makes a lot of sense.

**Comment by yongsoo** [comment]
@darkdarkdragon What do you think?

**Comment by darkdarkdragon** [comment]
@yongsoo Sounds reasonable. I'll move it under input fields

**Comment by darkdarkdragon** [comment]
moved:
rt-3271-after2

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
