### PR TITLE
[TASK] move settings to rippletradecom (RT-2990)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
move all the client specific settings from root scope to clients.rippletrade

setting moved
persistUnlock
lastSeenTxDate
trade_currency_pairs
txQueue

### CODE REVIEW

**Comment by vhpoet** [comment]
Can you create a function or something to do this check? Seems like we're using this a lot `if(data.clients && data.clients.rippletradecom && data.clients.rippletradecom.WHATEVER)`.

**Comment by darkdarkdragon** [comment]
@vhpoet done

**Comment by vhpoet** [comment]
@darkdarkdragon MUCH better. Can you please also rebase?

**Comment by vhpoet** [comment]
@darkdarkdragon the test fails on "settings utils should check invalid"

**Comment by darkdarkdragon** [comment]
@vhpoet fixed

**Comment by mrajvanshy** [comment]
LGTM

**Comment by mrajvanshy** [comment]
Please rebase

**Comment by rht** [comment]
@vhpoet Merge this?

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
