### PR TITLE
[FIX] Fix aligment of check box (RT-3001)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
make it same on windows and on mac

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
rt-3001-before

**Comment by darkdarkdragon** [comment]
after
rt-3001-after

**Comment by mrajvanshy** [comment]
LGTM

**Comment by rippletravis** [comment]
Visuals look good.

**Comment by MatthewPhinney** [comment]
LGTM

**Pull request merged**
