### PR TITLE
[FEATURE] Send,Exchange: Show Network Fee in confirmation page (RT-2650)

### PR DESCRIPTION
**Pull request by rht**
Send
2014-12-25-202439_1366x768_scrot

Exchange
2014-12-25-202348_1366x768_scrot

### CODE REVIEW

**Comment by rht** [comment]
@vhpoet It's a separate bug (reproducible). Though it means the network fee still works (that it shows number) even if the amount is undefined -> the PR is isolated from the bug ;)

@annatonger Yes, sure, I wrote this PR because:
1. It takes less time than the RT-2650 revamp.
2. It's better for user to know the network fee soon, long before RT-2650 is implemented.

**Comment by annatonger** [comment]
@rht can you implement the UI to be a blue link that says "show network fee" and then when you click on it, the network fee is shown and the link changes to "hide network fee". (like what's in the ticket rt-2650)

**Comment by rht** [comment]
@annatonger
- Ok I will implement the "show network fee" and "hide network fee", but still with the old text. The new confirmation page UI/text seems to be less linear (i.e. less directly-dictatable to the blind / more "run-on sentences" UI).
- I will remove "expected" from "You will pay an expected network fee for".

**Comment by rht** [comment]
Related to the undefined BTC https://ripplelabs.atlassian.net/browse/RT-1486

**Comment by rippletravis** [comment]
Change "expected network fee for" to "expected network fee of".

**Comment by rht** [comment]
When shown
2015-01-09-160447_854x347_scrot

When hidden
2015-01-09-160500_847x268_scrot

**Comment by rht** [comment]
"You will pay at most" excludes the network fee.
Should the ```1%``` be replaced with 1% + (network fee) / (transaction amount) ?

May not be a big deal for huge transaction, but it's huge for microtransactions.

**Comment by annatonger** [comment]
You're right, let me think about this and get back to you

**Comment by annatonger** [comment]
@rht, just use the text "Ripple network fee: .02 XRP"

**Comment by rht** [comment]
So it is a part of "You will pay at most"?
i.e.
You will pay at most
[ n BTC \pm 1% ]
Ripple network fee:   _Hide network fee_
[ 0.02 XRP ]

**Comment by rht** [comment]
Can't upload the screenshot somehow, but it looks just like

You will pay at most
```undefined BTC \pm 1% ```
Ripple network fee:   _Hide network fee_
``` 0.02 XRP ```

**Pull request closed without merging**
