### PR TITLE
[TASK] set send threshold to 0.1% (RT-2205)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
set maximum send and conversion threshold to 0.1%

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after1
rt-2205-after1

**Comment by darkdarkdragon** [comment]
after2
rt-2205-after2

**Comment by annatonger** [comment]
Ivan, this should only be for converting, not sending

**Comment by darkdarkdragon** [comment]
@annatonger In task description: "When using the Convert feature or sending a payment,"
So what me to do? Revert back changes on send?

**Comment by annatonger** [comment]
Ah okay, my bad. This is fine with me then.

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
