### PR TITLE
[FIX] Option to edit the send_max (RT-3205)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Advanced settings: option to edit the send_max of a Send and Simple Trade

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3205-after

**Comment by darkdarkdragon** [comment]
before
rt-3205-before

**Comment by darkdarkdragon** [comment]
after
rt-3205-after

**Comment by annatonger** [comment]
can you please make this to the Release branch?

the UI LGTM

**Pull request closed without merging**
