### PR TITLE
Grunt -> Gulp

### PR DESCRIPTION
**Pull request by vhpoet**

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by mrajvanshy** [comment]
@vhpoet Are we going to need to change the tests now?

**Comment by vhpoet** [comment]
@mrajvanshy just updated the travis, let's see if it works.

**Comment by h0vhannes** [comment]
It seems to me that you removed roost code from index.html. Roost notifications will not work in this case.

**Comment by vhpoet** [comment]
@h0vhannes fixed

**Comment by darkdarkdragon** [comment]
@vhpoet in .travis.yml change
```
  - "cp test/travis/config-travis.js src/js/config.js"
```
to
```
  - "cp test/travis/config-travis.js config.js"
```

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
