### PR TITLE
[FIX] Balance widget: 4 decimal places (RT-3390)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Show 4 decimal places on XRP in balance widget

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3390-before

**Comment by darkdarkdragon** [comment]
after
rt-3390-after

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
