### PR TITLE
[TASK] renaming tabs controllers (RT-3014)

### PR DESCRIPTION
**Pull request by Mesrop**
to avoid conflicts I think we need to merge this tasks branches daily.
So now I am making PR for Tabs.

### CODE REVIEW

**Comment by vhpoet** [comment]
@Mesrop nice, please rebase.

**Comment by Mesrop** [comment]
@vhpoet rebased and updated

**Comment by jublo** [comment]
@Mesrop There are still merge conflicts—more rebasing needed.

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
