### PR TITLE
attempt 2: add original ripplers subreddit

### PR DESCRIPTION
**Pull request by themusicgod1**
add original ripplers subreddit to readme, without accidentally adding other changes.

### CODE REVIEW

**Comment by jublo** [comment]
LGTM

**Comment by rht** [comment]
LGTM

If you want it even cleaner, use git squash.
http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by MatthewPhinney** [comment]
Please squash your commits.

**Comment by annatonger** [comment]
@themusicgod1 ?

**Comment by themusicgod1** [comment]
trying to get access to a machine with git so I can try squashing, its' been a few days

**Pull request closed without merging**
