### PR TITLE
[FIX] better error messages (RT-2480)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
better error messages if auth server is unreachable

### CODE REVIEW

**Comment by annatonger** [comment]
Thanks. Can you actually change the text to "Your account cannot be accessed at the moment. Please try again later."

(the actual reason why the person may not be able to access the account may not just be DDOS, but also the authentication server being unreachable)

**Comment by darkdarkdragon** [comment]
@annatonger done

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
Please rebase

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
