### PR TITLE
[FIX] BTC: Show "loading" (RT-3340)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Show btc2ripple module as loading while it is loading

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3340-after

**Comment by mrajvanshy** [comment]
LGTM

**Comment by yongsoo** [comment]
Please rebase

**Comment by darkdarkdragon** [comment]
@yongsoo done

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
