### PR TITLE
[TASK] css: minify output

### PR DESCRIPTION
**Pull request by rht**
Size reduction
312 KB -> 248 KB

### CODE REVIEW

**Comment by rht** [comment]
on size reduction: running image compression reduces size from 3.2 MB to 2.7 MB.
Want a PR on this?

Though I think the load performance won't improve much if the server already uses gzip header.

**Comment by rht** [comment]
pagespeed and yslow score for ripple-client 1.3.2 http://gtmetrix.com/reports/rippletrade.com/06qdOPUf

**Comment by vhpoet** [comment]
LGTM

**Comment by vhpoet** [comment]
@rht Please also make a PR on image compression.

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
