### PR TITLE
[FIX] Btc2ripple: show appropriate error(RT-3334)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Btc2ripple: show appropriate error message when you've
already signed up for btc2ripple using another email address

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3334-before

**Comment by darkdarkdragon** [comment]
after
rt-3334-after

**Comment by mrajvanshy** [comment]
LGTM

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
