### PR TITLE
Develop rt 2975

### PR DESCRIPTION
**Pull request by darkdarkdragon**
this also fixes https://ripplelabs.atlassian.net/browse/RT-3093

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by jublo** [comment]
@darkdarkdragon On an unimportant side note (just my two cents), you could have used a more descriptive pull request title, appending the JIRA number in brackets.

**Comment by darkdarkdragon** [comment]
@jublo yeah, was too quick on that :) when there is just one commit in pr, github takes commit description as pr description, but if there is more commits it sets such bad description for pr. Now I'm paying more attention to pr descriptions.

**Comment by jublo** [comment]
@darkdarkdragon Thanks!

**Pull request closed without merging**
