### PR TITLE
[FEATURE] Dismiss locale popup on Esc (RT-3280)

### PR DESCRIPTION
**Pull request by jublo**
Use `rp-popup(rp-popup-dismiss-on-esc)` attribute to allow dismissing the popup when the user presses the [Esc] key while the popup is shown.

### CODE REVIEW

**Comment by vhpoet** [comment]
@jublo can we just make this a default?

**Comment by jublo** [comment]
@vhpoet Sure—if there aren’t any popups that needs to run custom code on cancel?

**Comment by vhpoet** [comment]
esc should call the same action as cancel

**Comment by jublo** [comment]
so esc should just call `popup.cancel()`?

**Comment by rht** [comment]
unlock.jade popup has esc as cancel, but with different implementation.

**Comment by jublo** [comment]
From my checks, these are the only 2 occurrences of the popup, so can I generalize the ESC button press as default for both of these?

**Comment by vhpoet** [comment]
yep, esc should call popup.cancel

**Comment by jublo** [comment]
`popup.cancel()` is not a function defined in the popup service. Pressing ESC now cancels any popup that was created with a `rp-popup` directive (thus excluding the unlock popup, which is invoked directly using the service, but that has its own ESC code).

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
