### PR TITLE
[FEATURE] Send,Exchange: Show Network Fee in confirmation page

### PR DESCRIPTION
**Pull request by rht**
Accidentally closed https://github.com/ripple/ripple-client/pull/2040 and the reopen button is disabled.

Latest text should look like:
You will pay at most
```undefined BTC \pm 1% ```
\+ Ripple network fee:   _Hide network fee_
``` 0.02 XRP ```

### CODE REVIEW

**Comment by rht** [comment]
2015-01-13-180247_849x306_scrot

**Comment by annatonger** [comment]
@rht- can you put the whole fee in one line with "Ripple network fee", without the big grey box. In the same size as "Ripple network fee". And remove the "Hide network fee" link, it doesn't make sense right now.

**Comment by rht** [comment]
Sure, plus it saves vertical space, though it breaks the pattern that currency amount needs to be put in a grey box. But then the new Send page doesn't use any grey boxes.

exchange

# Before (upstream/develop as of https://github.com/ripple/ripple-client/commit/2203ce2bad398a434e5089a29260c11ddcde41eb)
2015-01-15-210043_401x412_scrot

# After
2015-01-15-210228_415x462_scrot

**Comment by rht** [comment]
send
**Before (upstream/develop as of https://github.com/ripple/ripple-client/commit/2203ce2bad398a434e5089a29260c11ddcde41eb)**
2015-01-15-205945_443x144_scrot

**After**
2015-01-15-205551_458x166_scrot

**Comment by mrajvanshy** [comment]
LGTM

**Comment by mrajvanshy** [comment]
Need to rebase

**Comment by vhpoet** [comment]
LGTM

**Comment by rippletravis** [comment]
Works for me.

**Pull request merged**
