### PR TITLE
[FIX] do not ask pass on unfunded (RT-3433)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
when on unfunded account transaction is getting added
to rpTxQueue, do not ask password - it is not needed

### CODE REVIEW

**Comment by annatonger** [comment]
We still need to queue a trustSet transaction though. Will this break that?

**Comment by darkdarkdragon** [comment]
this patch does not change functionality, it just removes asking password in place where it is not used

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
