### PR TITLE
[FEATURE] Highlight new/changed orders (RT-3278)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Advanced Trade: highlight new/updated orders
with green/red color.

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3278-after

**Comment by vhpoet** [comment]
@darkdarkdragon currently we use green to highlight "my orders" in orderbook, maybe we should use a different color?

**Comment by darkdarkdragon** [comment]
another try:
rt-3278-after2

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
