### PR TITLE
[FIX] Gateways: Transposed layout for xs, sm screens (RT-2585)

### PR DESCRIPTION
**Pull request by jublo**

### CODE REVIEW

**Comment by mrajvanshy** [comment]
LGTM

**Comment by annatonger** [comment]
@MatthewPhinney

**Comment by mrajvanshy** [comment]
Needs to be rebased again

**Comment by jublo** [comment]
Rebasing.

**Comment by jublo** [comment]
bildschirmfoto 2015-03-13 um 20 41 06

Sigh, rebasing this took 1 hour today already, so this annoys me.

**Comment by jublo** [comment]
@annatonger Rebased successfully and tested.

**Comment by annatonger** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
