### PR TITLE
[TASK] Disable federation for non KYCd (RT-3488)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Disable federation for non KYCd people

This commit is not tested with real backend because required changes to it still not deployed into production.

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3488-after

**Comment by vhpoet** [comment]
LGTM

**Comment by annatonger** [comment]
@darkdarkdragon can you update your PR to make the error message better?
It should say: "You can't send to a federation address on Ripple Trade unless your identity is verified. To verify your identity, log out and log back in, and you'll be prompted to start the identity verification process."

**Comment by darkdarkdragon** [comment]
done
rt-3488-after2

**Pull request merged**
