### PR TITLE
[FIX] Trade: Show loading for orderbooks(RT-3402)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Orderbook: Show loading instead of "no bids"

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3402-before

**Comment by darkdarkdragon** [comment]
after
rt-3402-after

**Comment by vhpoet** [comment]
@darkdarkdragon can you make it centered, so that it doesn't touch the borders?

**Comment by darkdarkdragon** [comment]
@vhpoet done
rt-3402-after2

**Comment by mrajvanshy** [comment]
LGTM

**Comment by vhpoet** [comment]
@darkdarkdragon it's still touching the border.

**Comment by darkdarkdragon** [comment]
@vhpoet fixed
rt-3402-after3

**Comment by jublo** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
