### PR TITLE
Use binary account_tx

### PR DESCRIPTION
**Pull request by wltsmrz**

### CODE REVIEW

**Comment by sublimator** [comment]
You should do some perf tests for this, and perhaps use setTimeout or whatever, if you're busting the 16ms rule. Last time I looked the serdes was pretty slow. 

The new delivered_amount field may also be missing, something to ponder  ....

**Comment by sublimator** [comment]
re: 16ms rule, I mean the browser

**Comment by wltsmrz** [comment]
Last time I tested binary account_tx locally the difference wasn't very significant. ripple-lib has to map over the transactions and parse, so the difference should probably be more apparent on the rippled side.

**Comment by sublimator** [comment]
All adds up, think of the starving people in mobilopia

**Comment by sublimator** [comment]
On my machine i7 laptop on node/v8 it takes 0.16 seconds to convert the tx and meta for 200 transactions.

**Comment by wltsmrz** [comment]
What I meant was that the difference from the client perspective between requesting binary and non-binary account_tx isn't very significant (because, as noted, parsing is slow).

**Comment by sublimator** [comment]
When the server is slow to binary -> json, the client can still process
events.
If the client is slow to binary -> tx, it can cause lockups.

It's a simple fix anyway. Just yield to the event loop now and then, and
set a callback $somehow to resume processing.

**Comment by wltsmrz** [comment]
Agreed. I'll add some async.mapSeries / async.setImmediate to ripple-lib's requestAccountTransactions(). The interface won't change, so this pull request is still active & mergeable

**Comment by sublimator** [comment]
I was confused b4, thought this was a ripple lib request

**Comment by wltsmrz** [comment]
https://github.com/ripple/ripple-lib/pull/245

**Comment by vhpoet** [comment]
did you say delivered_amount is missing?

**Comment by sublimator** [comment]
Only the new json field 'delivered_amount' that is being injected.
DeliveredAmount will still be there as b4.

**Comment by wltsmrz** [comment]
grep -r "delivered_amount" yielded nothing. I think you'll be ok

https://github.com/ripple/ripple-client/blob/develop/src/js/util/jsonrewriter.js#L160-L162

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
