### PR TITLE
[TASK] Signup/Login form UI messed up (RT-3367)

### PR DESCRIPTION
**Pull request by Mesrop**

### CODE REVIEW

**Comment by vhpoet** [comment]
Please include before/after screenshots with UI change PRs. Also `font-size: 0` looks weird.

**Comment by Mesrop** [comment]
@vhpoet removed font-size: 0, tested on chrome,ff and safari.
after-rt3367
before-rt3367

**Comment by vhpoet** [comment]
LGTM

**Comment by Mesrop** [comment]
@vhpoet just squashed

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
