### PR TITLE
[TASK] No pairs message (RT-2992)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Trade settings tab: show "no pairs" messages
if there no pairs to edit

### CODE REVIEW

**Comment by jublo** [comment]
Can we please get an After screenshot what it looks like, @darkdarkdragon?

**Comment by mrajvanshy** [comment]
LGTM

**Comment by darkdarkdragon** [comment]
rt-2992

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
