### PR TITLE
[FIX] Currencies: Fix standard precision for BTC, XRP, LTC

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by mrajvanshy** [comment]
Why are we changing the precision of these currencies?

**Comment by rht** [comment]
Because 4 is not the canonical / standard precision of those currencies.
Unless I misunderstood "standard_precision" to be the display precision for convenience.

Technically they are the same, because the ripple ledger doesn't know of the standard precision of each currencies?

Oh, and speaking of standard precision, you cannot buy XRP for smaller than a drop (1e-6 XRP), but you can buy BTC for smaller than a satoshi (1e-8 BTC) and also for other currencies as long as IOU precision permits (1e-15).

**Comment by yongsoo** [comment]
Please consult with @annatonger .  We implemented very specific precision a few months back.

**Comment by rht** [comment]
Ok, @annatonger 

Answering my own last paragraph: because XRP is not an IOU (duh) and is the only currency stored as integer in the ledger. So you have to use XRR for XRP IOU smaller than a drop.

**Comment by rht** [comment]
Btw, the 4 as precision for the cryptocurrencies has been there since the beginning of currencies.js.

**Comment by rht** [comment]
But sending 1e-3 satoshi to a BTC bridge is not allowed.

**Comment by rht** [comment]
This PR's scope should be limited to about currency standard precision.
The trade precision question ("if I am allowed to send a drop to a BTC bridge?") is for another case.

At least for this PR, I think the code must consistently distinguish between 1. standard precision, 2. display precision (e.g. balance and notifications), 3. trade precision (the hard-coded 6 decimal digits in trade regardless of market's pip amount).
Maybe there is one more case: the precision for the smallest phenomenon in the network (so far, a drop?).

It is clear that '4' is display precision, not standard precision.
This "set XRP/BTC/LTC decimal points to 4" should live in rpamount filter (or in balance/notification), not in currencies.js.

**Comment by rht** [comment]
This will mess with the BTC/LTC display format in trust tab,
http://xkcd.com/1172/

**Comment by annatonger** [comment]
We spent a lot of time trying to fix the screwed up decimal precisions in Ripple Trade so I'm very hesitant to mess with it right now. If you change it, it will be screwed up in other places in the client... :( 

sorry

**Comment by jublo** [comment]
/me is worrying about the Balances sidebar and its tooltips… :scream:

**Pull request closed without merging**
