### PR TITLE
[FIX] Option to edit the send_max (RT-3205)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Advanced settings: option to edit the send_max of a Send and Simple Trade

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
after
rt-3205-after

**Comment by vhpoet** [comment]
@darkdarkdragon test failed

**Comment by darkdarkdragon** [comment]
@vhpoet This one is strange. I can't reproduce it on local machine, and it appears to be failing on all latest travis build

**Comment by vhpoet** [comment]
@darkdarkdragon yep that was an unrelated issue

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
