### PR TITLE
[FEATURE] Persistent widget settings (RT-2885)

### PR DESCRIPTION
**Pull request by jublo**

### CODE REVIEW

**Comment by annatonger** [comment]
@vhpoet @MatthewPhinney @mrajvanshy @yongsoo

**Comment by yongsoo** [comment]
This needs to be rebased.

**Comment by vhpoet** [comment]
again

**Comment by jublo** [comment]
Please review now.

**Comment by mrajvanshy** [comment]
@jublo Needs to be rebased again

**Comment by jublo** [comment]
@annatonger Long-running PR.

**Comment by jublo** [comment]
@mrajvanshy I don’t think this is ever going to be merged, is it.

**Comment by jublo** [comment]
Closing this pull request since no one seems to be working on it anymore.

**Pull request closed without merging**
