### PR TITLE
[FIX] Trade: fix trade pairs order edit (RT-3343)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Fix editing trade pairs order.
Clean trade pairs list - remove $$hashKey, remove duplicates.
Check trade pair before adding.

### CODE REVIEW

**Comment by mrajvanshy** [comment]
@darkdarkdragon please rebase

**Comment by darkdarkdragon** [comment]
@mrajvanshy done

**Comment by mrajvanshy** [comment]
LGTM

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
