### PR TITLE
[TASK] Test: Add Travis badge and code coverage

### PR DESCRIPTION
**Pull request by rht**
Wait until it shows up in http://direct.coveralls.io/r/ripple/

### CODE REVIEW

**Comment by annatonger** [comment]
@vhpoet @mrajvanshy @MatthewPhinney @yongsoo

**Comment by justmoon** [comment]
Enabled, let me know if I need to do anything else.

**Comment by vhpoet** [comment]
LGTM

**Comment by rht** [comment]
Note: this is still in progress.

In the first iteration, 97%, only ripple-client-debug.js is covered.
In the 2nd iteration, only config.js is covered; I'm still figuring (whenever it is possible) out make webpack working in karma so every single src/js/*.js can be covered.

And also branch coverage > line coverage, but coveralls.io doesn't have branch coverage enabled yet.

**Pull request merged**
