### PR TITLE
[TASK] Ability to move trade pairs (RT-2875)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Edit state for trade pairs: allow ability to move pairs around

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
rt-2875

**Comment by mrajvanshy** [comment]
I think we need to make the UI discoverable so users know they can move around the trade pairs. Right now there is no indication that this behavior is possible.

**Comment by darkdarkdragon** [comment]
@rippletravis fixed

**Comment by rippletravis** [comment]
I can still make the duplication happen, and I still can't see the grips/dots.

@mrajvanshy Are you able to see them now?

**Comment by darkdarkdragon** [comment]
@rippletravis Can you, please, check it here?
http://ripple.darkdragon.com.ua/#/settingstrade

**Comment by rippletravis** [comment]
Seems to be working there.

**Comment by mrajvanshy** [comment]
I can't see the dots on the PR environment either, but I can see them on http://ripple.darkdragon.com.ua/#/settingstrade

**Comment by annatonger** [comment]
Let's merge this then, it may be an issue with the PR environment

**Comment by mrajvanshy** [comment]
LGTM

**Comment by annatonger** [comment]
@yongsoo @vhpoet @MatthewPhinney

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
