### PR TITLE
[FIX] Convert fee in rewrited transaction to ripple.Amount

### PR DESCRIPTION
**Pull request by h0vhannes**
This patch converts fee field in the rewrited transaction from drops to ripple.Amount object

### CODE REVIEW

**Comment by vhpoet** [comment]
LGTM

**Comment by yongsoo** [comment]
Should this be on release branch @vhpoet?

**Comment by vhpoet** [comment]
@yongsoo it's ok here

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
